// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheChart: typeof import('./components/TheChart.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    WeatherHeader: typeof import('./components/WeatherHeader.vue')['default']
    WeatherTile: typeof import('./components/WeatherTile.vue')['default']
  }
}
