// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/TheChart copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCarousel: typeof import('./components/TheCarousel.vue')['default']
    TheChart: typeof import('./components/TheChart.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheForm: typeof import('./components/TheForm.vue')['default']
    TheGeolocation: typeof import('./components/TheGeolocation.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheSelect: typeof import('./components/TheSelect.vue')['default']
    WeatherHeader: typeof import('./components/WeatherHeader.vue')['default']
    WeatherTile: typeof import('./components/WeatherTile.vue')['default']
  }
}
